-- ============================================================
-- Migration 004: Rep mapping (SF display name → @keychain.com)
-- Emails verified against SF report (report1776197209262.csv).
-- 'Partnerships' is not a person; is_active = false.
-- ============================================================
insert into rep_mapping (sf_display_name, rep_email, rep_name, is_active)
values
  ('Aaron Jamieson',     'aaron.jamieson@keychain.com',     'Aaron Jamieson',     true),
  ('Alex Gold',          'alex.gold@keychain.com',          'Alex Gold',          true),
  ('Amy Wilcox',         'amy.wilcox@keychain.com',         'Amy Wilcox',         true),
  ('Andy Tripp',         'andy.tripp@keychain.com',         'Andy Tripp',         true),
  ('Ben Oliver',         'ben.oliver@keychain.com',         'Ben Oliver',         true),
  ('Brandon Henneman',   'brandon.henneman@keychain.com',   'Brandon Henneman',   true),
  ('Caroline Davidson',  'caroline.davidson@keychain.com',  'Caroline Davidson',  true),
  ('Chad Ross',          'chad.ross@keychain.com',          'Chad Ross',          true),
  ('Chessney Goodman',   'chessney.goodman@keychain.com',   'Chessney Goodman',   true),
  ('Christian Montoya',  'christian.montoya@keychain.com',  'Christian Montoya',  true),
  ('David Walsh',        'david.walsh@keychain.com',        'David Walsh',        true),
  ('Deena Byrne',        'deena.byrne@keychain.com',        'Deena Byrne',        true),
  ('Ellen Schryver',     'ellen.schryver@keychain.com',     'Ellen Schryver',     true),
  ('Emily Roberts',      'emily.roberts@keychain.com',      'Emily Roberts',      true),
  ('Gavin Menichini',    'gavin.menichini@keychain.com',    'Gavin Menichini',    true),
  ('Grant Patton',       'grant.patton@keychain.com',       'Grant Patton',       true),
  ('Jacqueline Fallacara','jackie.fallacara@keychain.com',  'Jacqueline Fallacara',true),
  ('Jade Shelton',       'jade.shelton@keychain.com',       'Jade Shelton',       true),
  ('Jenna Hackathorn',   'jenna.hackathorn@keychain.com',   'Jenna Hackathorn',   true),
  ('Jennifer Searles',   'jennifer.searles@keychain.com',   'Jennifer Searles',   true),
  ('Jonathan Kull',      'jonathan.kull@keychain.com',      'Jonathan Kull',      true),
  ('Jordan Cooper',      'cooper.jordan@keychain.com',      'Jordan Cooper',      true),
  ('Jordan Weitz',       'jordan@keychain.com',             'Jordan Weitz',       true),
  ('Julia Ott',          'julia.ott@keychain.com',          'Julia Ott',          true),
  ('Kayle Hill',         'kayle.hill@keychain.com',         'Kayle Hill',         true),
  ('Kim Ryng',           'kim.ryng@keychain.com',           'Kim Ryng',           true),
  ('Lyndsi Zapata',      'lyndsi.zapata@keychain.com',      'Lyndsi Zapata',      true),
  ('Max Lindemann',      'max.lindemann@keychain.com',      'Max Lindemann',      true),
  ('Maxwell Fenn',       'max.fenn@keychain.com',           'Maxwell Fenn',       true),
  ('Maya Bakshi',        'maya.bakshi@keychain.com',        'Maya Bakshi',        true),
  ('Nick Newell',        'nick.newell@keychain.com',        'Nick Newell',        true),
  ('Oscar Garza',        'oscar.garza@keychain.com',        'Oscar Garza',        true),
  ('Partnerships',       'partnerships@keychain.com',       'Partnerships',       false),
  ('Pete Wolfinger',     'pete.wolfinger@keychain.com',     'Pete Wolfinger',     true),
  ('Peter Self',         'peter.self@keychain.com',         'Peter Self',         true),
  ('Raghuram A',         'raghuram.a@keychain.com',         'Raghuram A',         true),
  ('Randall Lopez',      'randall.lopez@keychain.com',      'Randall Lopez',      true),
  ('Romy Lynch',         'romy@keychain.com',               'Romy Lynch',         true),
  ('Shane O''Connell',   'shane.oconnell@keychain.com',     'Shane O''Connell',   true),
  ('Taylor Mangum',      'taylor.mangum@keychain.com',      'Taylor Mangum',      true),
  ('Taylor Patterson',   'taylor.patterson@keychain.com',   'Taylor Patterson',   true),
  ('Taylor Tempel',      'taylor.tempel@keychain.com',      'Taylor Tempel',      true),
  ('Teddy Callow',       'teddy.callow@keychain.com',       'Teddy Callow',       true),
  ('Theo Staggers',      'theo.staggers@keychain.com',      'Theo Staggers',      true),
  ('Tyler Madden',       'tyler.madden@keychain.com',       'Tyler Madden',       true),
  ('Varun Pal',          'varun.pal@keychain.com',          'Varun Pal',          true),
  ('Wesley Phillips',    'wesley.phillips@keychain.com',    'Wesley Phillips',    true),
  ('Zachary Henault',    'zach.henault@keychain.com',       'Zachary Henault',    true),
  ('Zoe Valella',        'zoe.valella@keychain.com',        'Zoe Valella',        true);
